spring:
 application:
  name: Numerology

 #数据源的配置
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/numerology?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  password: 123456
  username: root

 #mybatis的配置
 mybatis:
  type-aliases-package: numerology.server
  mapper-locations: classpath:mapper/*.xml
  configuration:
   map-underscore-to-camel-case: on
